#!/bin/bash

#find Bin/Test -executable -type f -exec {} \;
tests=`find Bin/Test -executable -type f`

for test in $tests
do
	echo "Running Test " $test
	$test
	if [[ $? -ne 0 ]]; then
		echo
		echo "Aborting remaining tests."
		exit 1
	fi
done

