// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "Window.h"

static void callback(Fl_Widget* o, void*) {
  printf("%g     \r", ((Fl_Valuator*)o)->value());
  fflush(stdout);
}

Fl_Input *KaiInput=(Fl_Input *)0;

Fl_Button *KaiEnter=(Fl_Button *)0;

Fl_Text_Display *KaiOutputData=(Fl_Text_Display *)0;

Fl_Text_Display *KaiOutputContext=(Fl_Text_Display *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(510, 330, "KAI Console");
    w = o;
    { KaiInput = new Fl_Input(10, 296, 390, 24, "input:");
      KaiInput->labeltype(FL_NO_LABEL);
    } // Fl_Input* KaiInput
    { KaiEnter = new Fl_Button(430, 295, 70, 20, "Enter");
    } // Fl_Button* KaiEnter
    { KaiOutputData = new Fl_Text_Display(10, 5, 240, 285);
    } // Fl_Text_Display* KaiOutputData
    { KaiOutputContext = new Fl_Text_Display(260, 5, 240, 285);
    } // Fl_Text_Display* KaiOutputContext
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
