// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef Window_h
#define Window_h
#include <FL/Fl.H>
void StartKai();
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *KaiInput;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *KaiOutputData;
extern Fl_Text_Display *KaiOutputContext;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *KaiEnter;
#endif
