// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "Window.h"

static void callback(Fl_Widget* o, void*) {
  printf("%g     \r", ((Fl_Valuator*)o)->value());
  fflush(stdout);
}

Fl_Input *KaiInput=(Fl_Input *)0;

Fl_Text_Display *KaiOutputData=(Fl_Text_Display *)0;

Fl_Text_Display *KaiOutputContext=(Fl_Text_Display *)0;

Fl_Return_Button *KaiEnter=(Fl_Return_Button *)0;

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Quit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Network", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(510, 330, "KAI Console");
    w = o;
    { KaiInput = new Fl_Input(10, 296, 390, 24, "input:");
      KaiInput->labeltype(FL_NO_LABEL);
      KaiInput->when(FL_WHEN_CHANGED);
    } // Fl_Input* KaiInput
    { KaiOutputData = new Fl_Text_Display(10, 20, 240, 270);
    } // Fl_Text_Display* KaiOutputData
    { KaiOutputContext = new Fl_Text_Display(260, 20, 240, 270);
    } // Fl_Text_Display* KaiOutputContext
    { KaiEnter = new Fl_Return_Button(420, 295, 72, 25, "Enter");
    } // Fl_Return_Button* KaiEnter
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 510, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    o->end();
  } // Fl_Double_Window* o
  StartKai();
  w->show(argc, argv);
  return Fl::run();
}
