#pragma once

#include "KAI/Translator/Common.h"
#include "KAI/Translator/AstNodeBase.h"

KAI_BEGIN

// A node in the AST generated by a Parser
struct PiAstNodeEnumType
{
	enum Enum
	{
		None,
		Operation,
		List,
		Map,
		Set,
		Array,
		Continuation,
		TokenType,
		Object = TokenType,
	};

	struct Node : AstNodeBase<PiToken, PiAstNodeEnumType>
	{
		typedef AstNodeBase<PiToken, PiAstNodeEnumType> Parent;
		using typename Parent::Token;

		Node() : Parent(Enum::None) {  }
		Node(Enum e) : Parent(e) { }
		Node(Enum e, Token &tok) : Parent(e, tok) { }
		Node(Parent::Token tok) : Parent(tok) { }
	};
};

typedef PiAstNodeEnumType PiAstNodes;
typedef PiAstNodeEnumType::Node PiAstNode;

const char *ToString(PiAstNodes::Enum val);

KAI_END

