#pragma once

#include "KAI/Translator/Config.h"
#include "KAI/Translator/TokenBase.h"
#include "KAI/Translator/AstNodeBase.h"

KAI_BEGIN

struct RhoAstNodeEnumType
{
	enum Enum
	{
		None,
		Program,
		Ident,
		GetMember,
		Function,
		Block,
		Conditional,
		Assignment,
		Call,
		Increment,
		Decrement,
		TokenType,
		Positive,
		Negative,
		ArgList,
		IndexOp,

		ForEach,
		For,

		List,
		Map,
	};

	static const char *ToString(Enum val);

	struct Node : AstNodeBase<RhoToken, RhoAstNodeEnumType>
	{
		typedef AstNodeBase<RhoToken, RhoAstNodeEnumType> Parent;
		using typename Parent::Token;

		Node() : Parent(Enum::None) {  }
		Node(Enum e) : Parent(e) { }
		Node(Enum e, Token &tok) : Parent(e, tok) { }
		Node(Parent::Token tok) : Parent(tok) { }

		friend std::ostream &operator<<(std::ostream &out, Node const &node)
		{
			return out << ToString(node.type) << ": " << node.token;
		}
	};
};

typedef RhoAstNodeEnumType::Node RhoAstNode;

// A node in the AST generated by a Parser

KAI_END

