#pragma once

#include "KAI/KAI.h"
#include "KAI/Core/BasePointer.h"
#include "KAI/Core/AccessorBase.h"
#include "KAI/Core/Accessor.h"
#include "KAI/Core/PropertyBase.h"
#include "KAI/Core/MethodBase.h"
#include "KAI/Core/ClassBase.h"
#include "KAI/Core/Memory.h"
#include "KAI/Core/Registry.h"
#include "KAI/Core/Class.h"
#include "KAI/Core/ClassBuilder.h"
#include "KAI/Core/Pathname.h"

#include "KAI/Core/BuiltinTypes/Void.h"
#include "KAI/Core/FunctionBase.h"
#include "KAI/Core/TriColor.h"
#include "KAI/Core/Function.h"
#include "KAI/Core/MethodBase.h"
#include "KAI/Core/Method.h"
