
#ifdef KAI_HAVE_PRAGMA_ONCE
#	pragma once
#endif

#ifndef KAI_PLATFORM_PC_NETWORK_TCP_CLIENT_IMPL_H
#	define KAI_PLATFORM_PC_NETWORK_TCP_CLIENT_IMPL_H

KAI_PLATFORM_NETWORK_BEGIN

struct TcpClientImpl
{
};

KAI_PLATFORM_NETWORK_END

#endif // KAI_PLATFORM_PC_NETWORK_TCP_CLIENT_IMPL_H

//EOF
