// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "Window.h"

static void callback(Fl_Widget* o, void*) {
  printf("%g     \r", ((Fl_Valuator*)o)->value());
  fflush(stdout);
}

Fl_Input *KaiInput=(Fl_Input *)0;

static void cb_KaiInput(Fl_Input*, void*) {
  ;
}

Fl_Text_Display *KaiOutputData=(Fl_Text_Display *)0;

Fl_Text_Display *KaiOutputContext=(Fl_Text_Display *)0;

Fl_Return_Button *KaiEnter=(Fl_Return_Button *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(510, 330, "KAI Console");
    w = o; if (w) {/* empty */}
    { KaiInput = new Fl_Input(10, 296, 390, 24, "input:");
      KaiInput->labeltype(FL_NO_LABEL);
      KaiInput->callback((Fl_Callback*)cb_KaiInput);
      KaiInput->when(FL_WHEN_CHANGED);
    } // Fl_Input* KaiInput
    { KaiOutputData = new Fl_Text_Display(10, 5, 240, 285);
    } // Fl_Text_Display* KaiOutputData
    { KaiOutputContext = new Fl_Text_Display(260, 5, 240, 285);
    } // Fl_Text_Display* KaiOutputContext
    { KaiEnter = new Fl_Return_Button(410, 295, 72, 20, "Enter");
    } // Fl_Return_Button* KaiEnter
    o->end();
  } // Fl_Double_Window* o
  StartKai();
  w->show(argc, argv);
  return Fl::run();
}
