set nocompatible
set encoding=utf-8

" ***************************************************
" Vundle
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

call vundle#end()            " required
filetype plugin indent on    " required
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" ***************************************************

" Pathogen (NERDTree)
execute pathogen#infect()

filetype indent plugin on
syntax on
set mouse=a
set autoindent
set number
set relativenumber
set shiftwidth=4
set tabstop=4
set expandtab
set list listchars=tab:→\ ,trail:·
set list
set cursorline
set noswapfile

if has('gui_running')
  set guioptions-=T  " no toolbar
endif

hi CursorColumn cterm=NONE ctermbg=red ctermfg=white guibg=darkred guifg=white
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>


