// Autogenerated on [date]
// do not edit

#include "KAI/Test/Base.h"
#include "KAI/Tests/TestBinaryStream.h"
#include "KAI/Tests/TestCompiler.h"
#include "KAI/Tests/TestExecutor.h"
#include "KAI/Tests/TestFunction.h"
#include "KAI/Tests/TestMethod.h"
#include "KAI/Tests/TestObject.h"
#include "KAI/Tests/TestPathname.h"
#include "KAI/Tests/TestRegistry.h"
#include "KAI/Tests/TestTree.h"

#pragma comment(lib, "C:/Dev/KAI/Lib/Win32/Debug/library.lib")

void RegisterUnitTests(KAI_NAMESPACE_NAME::nstd::vector<KAI_NAMESPACE_NAME::Pointer<KAI_NAMESPACE_NAME::Test::Module> > &modules, KAI_NAMESPACE_NAME::Object scope)
{
	KAI_NAMESPACE_NAME::Pointer<KAI_NAMESPACE_NAME::Test::Module> module_SelfTests = scope.New<KAI_NAMESPACE_NAME::Test::Module>();
	module_SelfTests->SetName("SelfTests");
	Set(scope, KAI_NAMESPACE_NAME::Pathname("SelfTests"), module_SelfTests);
	modules.push_back(module_SelfTests);
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestBinaryStream>("TestBinaryStream");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestCompiler>("TestCompiler");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestExecutor>("TestExecutor");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestFunction>("TestFunction");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestMethod>("TestMethod");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestObject>("TestObject");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestPathname>("TestPathname");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestRegistry>("TestRegistry");
	module_SelfTests->AddSuite<KAI_NAMESPACE_NAME::Tests::TestTree>("TestTree");
}

//EOF

